### ISSUE TITLE
Lets add JSS

### ISSUE THREAD

**Issue by kof** [DSchau/css-in-js-playground#17]
- [ ] jss
- [ ] react-jss
- [ ] styled-jss

**Comment by kof** [comment]
Do you need help?

**Comment by DSchau** [comment]
Always down for PRs!

Not incredibly familiar with JSS, but does it require any kind of plugins? I'm using buble for the transpiler (which does not support the same/any plugins as babel), so that may complicate things.

We may need to, and be better off, ripping out the current transpiler and just using babel

**Comment by kof** [comment]
Nope, no build step required.

**Comment by DSchau** [comment]
I can definitely build this then :) Stay tuned!

**Comment by kof** [comment]
Ping me on gitter or twitter if you have questions.
